// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Env.webApiKey,
    appId: '1:168170333202:web:3737b9f02aff64b76d64cb',
    messagingSenderId: '168170333202',
    projectId: 'akilli-ajanda-flutter',
    authDomain: 'akilli-ajanda-flutter.firebaseapp.com',
    storageBucket: 'akilli-ajanda-flutter.firebasestorage.app',
    measurementId: 'G-WHEKK7F5YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.androidApiKey,
    appId: '1:168170333202:android:dbf59fb74440a3276d64cb',
    messagingSenderId: '168170333202',
    projectId: 'akilli-ajanda-flutter',
    storageBucket: 'akilli-ajanda-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.iosApiKey,
    appId: '1:168170333202:ios:266ede9f90c9c96a6d64cb',
    messagingSenderId: '168170333202',
    projectId: 'akilli-ajanda-flutter',
    storageBucket: 'akilli-ajanda-flutter.firebasestorage.app',
    iosBundleId: 'com.example.akilliAjandaFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.macosApiKey,
    appId: '1:168170333202:ios:266ede9f90c9c96a6d64cb',
    messagingSenderId: '168170333202',
    projectId: 'akilli-ajanda-flutter',
    storageBucket: 'akilli-ajanda-flutter.firebasestorage.app',
    iosBundleId: 'com.example.akilliAjandaFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Env.windowsApiKey,
    appId: '1:168170333202:web:68fc4d58b34688b96d64cb',
    messagingSenderId: '168170333202',
    projectId: 'akilli-ajanda-flutter',
    authDomain: 'akilli-ajanda-flutter.firebaseapp.com',
    storageBucket: 'akilli-ajanda-flutter.firebasestorage.app',
    measurementId: 'G-FGPT56D3YG',
  );
}
